# Mini-batch gradient descent

In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
reg = LinearRegression()
reg.fit(X_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [6]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [7]:
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.439933866156897

In [16]:
import random
class GDRegressor:
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        self.coef_=None
        self.intercept_=None
        self.lr=learning_rate
        self.epochs=epochs
        self.batch_size=batch_size

    def fit(self,X_train,y_train):
       # init your coef
       self.intercept_=0
       self.coef_=np.ones(X_train.shape[1])

       for i in range(self.epochs):
           for j in range(int(X_train.shape[0]/self.batch_size)):
               idx=random.sample(range(X_train.shape[0]),self.batch_size)
               y_hat=np.dot(X_train[idx],self.coef_)+self.intercept_
               # print('shape y_hate',y_hat.shape)
               intercept_der=-2*np.mean(y_train[idx]-y_hat)
               self.intercept_=self.intercept_ - (self.lr*intercept_der)
    
               coef_der=-2*np.dot((y_train[idx]-y_hat),X_train[idx])
               self.coef_=self.coef_-(self.lr*coef_der)

       print(self.intercept_,(self.coef_))

    def predict(self,X_test):
       return np.dot(X_test,self.coef_)+self.intercept_

In [27]:
mbr=GDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=60)

In [28]:
mbr.fit(X_train,y_train)

150.0332540669921 [  51.0286557   -89.39024304  368.4212808   266.63200577    1.99964273
  -48.84226302 -178.34212362  123.72533635  336.11800969  129.67412209]


In [29]:
y_pred=mbr.predict(X_test)

In [30]:
r2_score(y_test,y_pred)

0.44080889667477363

In [8]:
import random
random.sample(range(1,100),10)

[59, 8, 6, 97, 82, 56, 26, 67, 68, 96]

In [9]:
X_train[random.sample(range(1,100),10)]

array([[ 0.02354575,  0.05068012, -0.02021751, -0.03665608, -0.01395254,
        -0.01509241,  0.05968501, -0.03949338, -0.09643495, -0.01764613],
       [ 0.04897352,  0.05068012,  0.12313149,  0.0838437 , -0.10476542,
        -0.10089509, -0.06917231, -0.00259226,  0.03664373, -0.03007245],
       [-0.04183994, -0.04464164, -0.06656343, -0.04698463, -0.03734373,
        -0.04327577,  0.0486401 , -0.03949338, -0.0561531 , -0.01350402],
       [-0.07816532, -0.04464164, -0.01698407, -0.01255612, -0.00019301,
        -0.01352667,  0.07072993, -0.03949338, -0.04117617, -0.09220405],
       [-0.05637009, -0.04464164, -0.08057499, -0.08485599, -0.03734373,
        -0.0370128 ,  0.03391355, -0.03949338, -0.0561531 , -0.13776723],
       [-0.02730979,  0.05068012, -0.02345095, -0.01599898,  0.01356652,
         0.0127778 ,  0.02655027, -0.00259226, -0.01090325, -0.02178823],
       [ 0.08166637, -0.04464164,  0.03367309,  0.00810098,  0.0520932 ,
         0.05661859, -0.01762938,  0.03430886

### mini_batch by using SGDRegressor class of sklearn

In [31]:
from sklearn.linear_model import SGDRegressor

In [37]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.01)

In [38]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [39]:
sgd.coef_

array([ 24.02137227,   3.07168038,  63.80057191,  51.49537801,
        19.48262241,  13.73032406, -41.70549027,  41.24594901,
        65.94319743,  36.40781343])

In [40]:
sgd.intercept_

array([147.597838])

In [41]:
y_pred = sgd.predict(X_test)

In [42]:
r2_score(y_test,y_pred)

0.14909748325820238